 // File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTcgsDU5fWA0579QUrNOKXSNp_BvQ0yMg',
    appId: '1:436266040399:web:1087b7287e5d695a24fe3a',
    messagingSenderId: '436266040399',
    projectId: 'mathmattersapp',
    authDomain: 'mathmattersapp.firebaseapp.com',
    databaseURL: 'https://mathmattersapp-default-rtdb.firebaseio.com',
    storageBucket: 'mathmattersapp.appspot.com',
    measurementId: 'G-M2ZBJ3HRLQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBr5nrb7aMZJCZq_Tu536H_HA7tft8GBz0',
    appId: '1:436266040399:android:be7c3bf6d7ded46024fe3a',
    messagingSenderId: '436266040399',
    projectId: 'mathmattersapp',
    databaseURL: 'https://mathmattersapp-default-rtdb.firebaseio.com',
    storageBucket: 'mathmattersapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqAZyT_MPn8jWd2JrQrM093zZOP-y1o4o',
    appId: '1:436266040399:ios:bd4f4c678813911824fe3a',
    messagingSenderId: '436266040399',
    projectId: 'mathmattersapp',
    databaseURL: 'https://mathmattersapp-default-rtdb.firebaseio.com',
    storageBucket: 'mathmattersapp.appspot.com',
    iosClientId: '436266040399-h1o85ek3ns8q95p1qm5o1i7s2fg4u9rc.apps.googleusercontent.com',
    iosBundleId: 'com.mathmatters.MathMattersApp',
  );
}
